class Stats:
    def __init__(self):
        self.ATK = []
        self.ATK_p = []
        self.CR = []
        self.CD = []
        self.EM = []
        self.HP = []
        self.HP_p = []
        self.DEF = []
        self.DEF_p = []
        self.PDMG = []
        self.ANEMO_DMG = []
        self.GEO_DMG = []
        self.ELECTRO_DMG = []
        self.HYDRPO_DMG = []
        self.PYRO_DMG = []
        self.CRYO_DMG = []
        self.HEAL = []
        self.SHIELD = []
        self.ER = []